### ISSUE TITLE
fix attempt to open non-existent log file

### ISSUE THREAD

**Issue by cl-jay** [creativelive/mkimage-server#12]
Error: ENOENT, open '/mnt/logs/mkimage-access.log'
worker 9996, respawning in 1 second ...
worker 10002 running

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open '/mnt/logs/mkimage-access.log'
worker 10002, respawning in 1 second ...
worker 10008 running

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open '/mnt/logs/mkimage-access.log'
worker 10008, respawning in 1 second ...
worker 10015 running

No such destination exists in non-dev environments.

**Comment by JustinBeaudry** [comment]
Stale issue. Closing.
