### ISSUE TITLE
URLs beginning with /fit have http:// added to them causing nginx warnings.

### ISSUE THREAD

**Issue by cl-darren** [creativelive/mkimage-server#27]
Nginx consistently reports issues with mkimage URLs that begin with /fit/ which may be due to imageresizer.js adding an extra http:// into the request URL.  An example URL would look something like:

http://localhost:3020/fit/http://assets.creativelive.com/sites/default/files/HOP-09q4-BNR-CDI-640x360px.png

which if you attempt to curl give an Unauthorized error.  Removing the second http:// from the URL and doing the same replies with "could'd download from http://assets.creativelive.com, http error: 403" which seems more reasonable.

**Comment by JustinBeaudry** [comment]
Stale Issue. Closing.
